More cleanup of pipelight-plugin.

diff --git a/bin/pipelight-plugin.in b/bin/pipelight-plugin.in
--- a/bin/pipelight-plugin.in
+++ b/bin/pipelight-plugin.in
@@ -1,11 +1,8 @@
 #!/usr/bin/env bash
 VERSION="@@VERSION@@"
 PIPELIGHT_SHARE_PATH="@@PIPELIGHT_SHARE_PATH@@"
-
-# Global configuration
-LIBRARY_PATH="@@LIBRARY_PATH@@"
+PIPELIGHT_LIBRARY_PATH="@@PIPELIGHT_LIBRARY_PATH@@"
 PLUGIN_PATH="@@MOZ_PLUGIN_PATH@@"
-DEPENDENCY_INSTALLER_PATH="@@DEPENDENCY_INSTALLER@@"
 DEPENDENCY_INSTALLER_URL="https://bitbucket.org/mmueller2012/pipelight/raw/master/share/install-dependency.sig"
 ACCEPTALL=0
 
@@ -86,12 +83,12 @@ INSTALLDIR=""
 get_directories()
 {
 	if [ ! -z "$INSTALLDIR" ]; then return 0; fi
-	if [ ! -d "$LIBRARY_PATH" ]; then
-		echo "ERROR: Failed to find $LIBRARY_PATH." >&2
+	if [ ! -d "$PIPELIGHT_LIBRARY_PATH" ]; then
+		echo "ERROR: Failed to find $PIPELIGHT_LIBRARY_PATH." >&2
 		exit 1
 	fi
 
-	LIBRARY_PATH=$(realpath "$LIBRARY_PATH")
+	PIPELIGHT_LIBRARY_PATH=$(realpath "$PIPELIGHT_LIBRARY_PATH")
 	PLUGIN_PATH=$(realpath "$PLUGIN_PATH")
 
 	# Global installation
@@ -239,7 +236,7 @@ enable_plugin()
 		return 1
 	fi
 
-	local src="$LIBRARY_PATH/libpipelight-$PLUGIN.so"
+	local src="$PIPELIGHT_LIBRARY_PATH/libpipelight-$PLUGIN.so"
 	local dst="$INSTALLDIR/libpipelight-$PLUGIN.so"
 
 
@@ -247,7 +244,7 @@ enable_plugin()
 		if is_additional_plugin "$PLUGIN"; then
 			echo "ERROR: You first need to call this program with: --unlock $PLUGIN" >&2
 		else
-			echo "ERROR: Your system is missing a copy of $LIBRARY_PATH/libpipelight.so at $src" >&2
+			echo "ERROR: Your system is missing a copy of $PIPELIGHT_LIBRARY_PATH/libpipelight.so at $src" >&2
 		fi
 		return 1
 	fi
@@ -269,7 +266,7 @@ enable_plugin()
 		return 1
 	fi
 
-	local srclnk="$LIBRARY_PATH/libpipelight-$PLUGIN.so"
+	local srclnk="$PIPELIGHT_LIBRARY_PATH/libpipelight-$PLUGIN.so"
 
 	if ! ln -s "$srclnk" "$dst"; then
 		echo "ERROR: Failed to create symlink from $src to $dst." >&2
@@ -464,7 +461,7 @@ create_mozilla_plugins()
 		local skip_additional=1
 	fi
 
-	local src="$LIBRARY_PATH/libpipelight.so"
+	local src="$PIPELIGHT_LIBRARY_PATH/libpipelight.so"
 
 	if [ ! -f "$src" ]; then
 		echo "ERROR: Can't find Pipelight installation at $src." >&2
@@ -473,7 +470,7 @@ create_mozilla_plugins()
 
 	# Create copy of the original plugin in libpipelight-*.so
 	for entry in "${PLUGIN_LIST[@]}"; do
-		local dst="$LIBRARY_PATH/libpipelight-$entry.so"
+		local dst="$PIPELIGHT_LIBRARY_PATH/libpipelight-$entry.so"
 
 		if [ -e "$dst" ]; then
 			if ! rm -f "$dst" 2>/dev/null; then
@@ -506,7 +503,7 @@ remove_mozilla_plugins()
 	fi
 
 	for entry in "${PLUGIN_LIST[@]}"; do
-		local dst="$LIBRARY_PATH/libpipelight-$entry.so"
+		local dst="$PIPELIGHT_LIBRARY_PATH/libpipelight-$entry.so"
 
 		if [ -e "$dst" ] && ! rm -f "$dst" 2>/dev/null; then
 			echo "ERROR: Failed to remove $dst." >&2
@@ -566,6 +563,7 @@ lock_plugin()
 
 update_dependency_installer()
 {
+	local dependencyinstaller="$PIPELIGHT_SHARE_PATH/install-dependency"
 	local tmpfile=$(mktemp)
 	[ -f "$tmpfile" ] || return 1
 
@@ -597,14 +595,14 @@ update_dependency_installer()
 
 	# Check if something has changed by comparing the sha256sum
 	local sha="$(sha256sum "$decfile" | cut -d' ' -f1)"
-	if [ -f "$DEPENDENCY_INSTALLER_PATH" ] && [ "$sha" == "$(sha256sum "$DEPENDENCY_INSTALLER_PATH" | cut -d' ' -f1)" ]; then
+	if [ -f "$dependencyinstaller" ] && [ "$sha" == "$(sha256sum "$dependencyinstaller" | cut -d' ' -f1)" ]; then
 		rm "$decfile"
 		echo ""
 		echo "Script dependency-installer is already up-to-date."
 		return 0
 	fi
 
-	if ! install -m 0755 "$decfile" "$DEPENDENCY_INSTALLER_PATH" 2>/dev/null; then
+	if ! install -m 0755 "$decfile" "$dependencyinstaller" 2>/dev/null; then
 		rm "$decfile"
 		echo ""
 		echo "ERROR: Root rights required to replace dependency-installer script" >&2
