Add system check utility

diff --git a/bin/pipelight-plugin b/bin/pipelight-plugin
--- a/bin/pipelight-plugin
+++ b/bin/pipelight-plugin
@@ -10,6 +10,8 @@ DEPENDENCY_INSTALLER_PATH="@@DEPENDENCY_INSTALLER@@"
 DEPENDENCY_INSTALLER_URL="https://bitbucket.org/mmueller2012/pipelight/raw/master/share/install-dependency.sig"
 PIPELIGHT_PUBKEY="@@PIPELIGHT_PUBKEY@@"
 PLUGINLOADER64_EXISTS="@@PLUGINLOADER64_EXISTS@@"
+WINE_PATH="@@WINE_PATH@@"
+WINE_CHECK="@@WINE_CHECK@@"
 ACCEPTALL=0
 
 # Supported plugins
@@ -51,6 +53,7 @@ usage()
 	echo "  --disable-all               disable all plugins"
 	echo "  --list-enabled              list enabled plugins for the current user"
 	echo "  --list-enabled-all          list all enabled plugins"
+	echo "  --system-check              do a system check"
 	echo "  --help                      shows this help"
 	echo "  --version                   shows the current version of Pipelight"
 	echo ""
@@ -402,6 +405,49 @@ list_all_enabled_plugins()
 	return 0
 }
 
+# > List all enabled plugins
+check_system()
+{
+	local retval=0
+
+	echo ">> 32 bit <<"
+	WINEARCH=win32 WINEPREFIX=~/.wine-pipelight "${WINE_PATH}" "${WINE_CHECK}.exe"
+	if [ "$?" -ne "0" ]; then
+		retval=1
+	fi
+	echo ""
+	echo "Checking libraries..."
+	WINEARCH=win32 WINEPREFIX=~/.wine-pipelight "${WINE_PATH}" --check-libs
+	if [ "$?" -eq "0" ]; then
+		echo "Libraries: PASSED"
+	else
+		echo "Libraries: FAILURE"
+		retval=1
+	fi
+
+	if [ ! -x "${WINE_PATH}64" ] || [ ! -x "${WINE_CHECK}64.exe" ]; then
+		return $retval
+	fi
+
+	echo ""
+	echo ">> 64 bit <<"
+	WINEARCH=win64 WINEPREFIX=~/.wine-pipelight64 "${WINE_PATH}64" "${WINE_CHECK}64.exe"
+	if [ "$?" -ne "0" ]; then
+		retval=1
+	fi
+	echo ""
+	echo "Checking libraries..."
+	WINEARCH=win64 WINEPREFIX=~/.wine-pipelight64 "${WINE_PATH}64" --check-libs
+	if [ "$?" -eq "0" ]; then
+		echo "Libraries: PASSED"
+	else
+		echo "Libraries: FAILURE"
+		retval=1
+	fi
+
+	return $retval
+}
+
 # > Create/Remove mozilla plugin copies
 # arguments:
 # $1	- Only change this plugin (optional, only used internally)
@@ -613,6 +659,10 @@ while [[ $# > 0 ]] ; do
 			;;
 		--list-enabled-all)
 			if ! list_all_enabled_plugins; then RET=1; fi
+			;;
+
+		--system-check)
+			if ! check_system; then RET=1; fi
 			;;
 
 		--create-mozilla-plugins)
