Make remaining parts of Pipelight FreeBSD compatible

diff --git a/bin/pipelight-plugin.in b/bin/pipelight-plugin.in
--- a/bin/pipelight-plugin.in
+++ b/bin/pipelight-plugin.in
@@ -580,7 +580,7 @@ update_dependency_installer()
 	[ -f "$tmpfile" ] || return 1
 
 	# Grab the latest version if the dependency-installer script
-	if ! wget -O "$tmpfile" "$DEPENDENCY_INSTALLER_URL"; then
+	if ! download_file "$tmpfile" "$DEPENDENCY_INSTALLER_URL"; then
 		echo ""
 		echo "ERROR: Failed to download latest dependency-installer script" >&2
 		rm "$tmpfile"
@@ -626,6 +626,33 @@ update_dependency_installer()
 	echo "Script dependency-installer has been updated to version $sha"
 	return 0
 }
+
+# Use fetch on FreeBSD if wget is not available
+if command -v wget >/dev/null 2>&1; then
+	download_file()
+	{
+		wget -O "$1" "$2"
+	}
+elif command -v fetch >/dev/null 2>&1; then
+	download_file()
+	{
+		fetch -o "$1" "$2"
+	}
+else
+	download_file()
+	{
+		echo "ERROR: Could neither find wget nor fetch. Unable to download file!" >&2
+		return 1
+	}
+fi
+
+# Use shasum instead of sha256sum on MacOS / *BSD
+if ! command -v sha256sum >/dev/null 2>&1 && command -v shasum >/dev/null 2>&1; then
+	sha256sum()
+	{
+		shasum -a 256 "$1"
+	}
+fi
 
 # Print usage message when no arguments are given at all
 if [ $# -eq 0 ]; then
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21,6 +21,7 @@ wine64path=""
 quietinstallation="true"
 nogpuaccel="false"
 debug="false"
+downloader=""
 
 usage ()
 {
@@ -28,7 +29,7 @@ usage ()
 	echo "Usage: ./configure [--prefix=PREFIX] [--debug]"
 	echo "                   [--moz-plugin-path=PATH] [--gcc-runtime-dlls=PATH]"
 	echo "                   [--show-installation-dialogs] [--no-gpu-accel]"
-	echo "                   [--cxx]"
+	echo "                   [--cxx] [--downloader]"
 	echo " 32-bit options:"
 	echo "                   [--win32-prebuilt] [--win32-cxx=COMPILER]"
 	echo "                   [--win32-static] [--win32-flags=FLAGS]"
@@ -76,12 +77,19 @@ while [[ $# > 0 ]] ; do
 			quietinstallation="false"
 			;;
 
-                --cxx=*)
-                        cxx="${CMD#*=}"
-                        ;;
-                --cxx)
-                        cxx="$1"; shift
-                        ;;
+		--cxx=*)
+			cxx="${CMD#*=}"
+			;;
+		--cxx)
+			cxx="$1"; shift
+			;;
+
+		--downloader=*)
+			downloader="${CMD#*=}"
+			;;
+		--downloader)
+			downloader="$1"; shift
+			;;
 
 		--debug)
 			debug="true"
@@ -212,6 +220,19 @@ if [ "$win64" == "true" ] && [ -z "$wine64path" ]; then
 	wine64path="$winepath/../wine64"
 fi
 
+if [ -z "$downloader" ]; then
+	if [ "$win32cxx" == "prebuilt" ] || [ "$win64cxx" == "prebuilt" ]; then
+		if command -v wget >/dev/null 2>&1; then
+			downloader="wget -O"
+		elif command -v fetch >/dev/null 2>&1; then
+			downloader="fetch -o"
+		else
+			echo "ERROR: Could neither find wget nor fetch! Please use --downloader to specify a program."
+			exit 1
+		fi
+	fi
+fi
+
 # Get the version number
 changelog=$(head -n1 debian/changelog)
 if [[ "$changelog" =~ \((.*)\)\ (UNRELEASED)? ]]; then
@@ -258,8 +279,9 @@ gccruntimedlls=$(resolvepath "$gccruntimedlls")
 	echo "# General"
 	echo "version=$version"
 	echo "prefix=$prefix"
-	echo "mozpluginpath=$mozpluginpath"
-	echo "gccruntimedlls=$gccruntimedlls"
+	echo
+	echo "# Prebuilt"
+	echo "downloader=$downloader"
 	echo ""
 	echo "# Linux"
 	echo "cxx=$cxx"
@@ -276,6 +298,8 @@ gccruntimedlls=$(resolvepath "$gccruntimedlls")
 	echo "wine64path=$wine64path"
 	echo ""
 	echo "# Other settings"
+	echo "mozpluginpath=$mozpluginpath"
+	echo "gccruntimedlls=$gccruntimedlls"
 	echo "quietinstallation=$quietinstallation"
 	echo "nogpuaccel=$nogpuaccel"
 	echo "debug=$debug"
diff --git a/share/install-dependency b/share/install-dependency
--- a/share/install-dependency
+++ b/share/install-dependency
@@ -123,14 +123,7 @@ download()
 	local trycount=3
 	local tmpfile=$(mktemp_with_ext "$EXT")
 	[ -f "$tmpfile" ] || return 1
-
-	local filesize="$(wget "$URL" --spider --server-response -O - 2>&1 | sed -ne '/Content-Length/{s/.*: //;p}')"
-	local re='^[0-9]+$'
-	if [[ "$filesize" -eq "0" ]] || ! [[ "$filesize" =~ $re ]]; then
-		filesize="N/A"
-	else
-		filesize=$(($filesize/(1024*1024)))
-	fi
+	local filesize=$(get_download_size "$URL")
 
 	# Download to tmpfile
 	while true; do
@@ -148,7 +141,7 @@ download()
 			return 1
 		fi
 
-		wget -O "$tmpfile" "$URL" 2>&1 | progressbar "Please wait, downloading ..." "Downloading $DEP ($filesize MiB)"
+		download_file "$tmpfile" "$URL" 2>&1 | progressbar "Please wait, downloading ..." "Downloading $DEP ($filesize MiB)"
 		if [ -f "$tmpfile" ] && [ "$SHA" == "$(sha256sum "$tmpfile" | cut -d' ' -f1)" ]; then
 			break
 		fi
@@ -740,6 +733,43 @@ install_triangleplayer()
 	# Successful
 	return 0
 }
+
+# Use fetch on FreeBSD if wget is not available
+if command -v wget >/dev/null 2>&1; then
+	download_file()
+	{
+		wget -O "$1" "$2"
+	}
+	get_download_size()
+	{
+		local filesize="$(wget -O- "$1" --spider --server-response 2>&1 | sed -ne '/Content-Length/{s/.*: //;p}')"
+		local re='^[0-9]+$'
+		if [[ "$filesize" -ne "0" ]] && [[ "$filesize" =~ $re ]]; then
+			echo "$(($filesize/(1024*1024)))"
+		else
+			echo "N/A"
+		fi
+	}
+elif command -v fetch >/dev/null 2>&1; then
+	download_file()
+	{
+		fetch -o "$1" "$2"
+	}
+	get_download_size()
+	{
+		echo "N/A"
+	}
+else
+	download_file()
+	{
+		echo "ERROR: Could neither find wget nor fetch. Unable to download file!" >&2
+		return 1
+	}
+	get_download_size()
+	{
+		echo "N/A"
+	}
+fi
 
 # Use shasum instead of sha256sum on MacOS / *BSD
 if ! command -v sha256sum >/dev/null 2>&1 && command -v shasum >/dev/null 2>&1; then
