configure: try to auto-detect mingw compiler, link statically by default

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,14 +2,13 @@
 
 # Default configuration
 version="unknown"
-prefix="/usr/local/"
+prefix="/usr/local"
+winepath="/opt/wine-compholio"
 mozpluginpath="/usr/lib/mozilla/plugins"
-gccruntimedlls="/usr/lib/gcc/i686-w64-mingw32/4.6/"
-winepath="/opt/wine-compholio/bin/wine"
+gccruntimedlls=""
+win32cxx=""
+win32flags=""
 quietinstallation="true"
-win32cxx="i686-w64-mingw32-g++"
-win32flags=
-pluginloader="pluginloader.exe"
 nogpuaccel="false"
 
 usage ()
@@ -17,9 +16,9 @@ usage ()
 	echo ""
 	echo "Usage: ./configure [--prefix=PREFIX] [--wine-path=PATH]"
 	echo "                   [--moz-plugin-path=PATH] [--gcc-runtime-dlls=PATH]"
-	echo "                   [--show-installation-dialogs] [--win32-static]"
-	echo "                   [--win32-prebuilt] [--win32-cxx=COMPILER] [--no-gpu-accel]"
-	echo "                   [--pluginloader-name=NAME] [--win32-flags=FLAGS]"
+	echo "                   [--win32-prebuilt] [--win32-cxx=COMPILER]"
+	echo "                   [--win32-static] [--win32-flags=FLAGS]"
+	echo "                   [--show-installation-dialogs] [--no-gpu-accel]"
 	echo ""
 }
 
@@ -79,13 +78,6 @@ while [[ $# > 0 ]] ; do
 			win32flags="$win32flags $1"; shift
 			;;
 
-		--pluginloader-name=*)
-			pluginloader=${CMD#*=}
-			;;
-		--pluginloader-name)
-			pluginloader="$1"; shift
-			;;
-
 		--no-gpu-accel)
 			nogpuaccel="true"
 			;;
@@ -100,6 +92,26 @@ while [[ $# > 0 ]] ; do
 	esac
 done
 
+# Try to autodetect compiler
+if [ -z "$win32cxx" ]; then
+	if command -v i686-w64-mingw32-g++ >/dev/null 2>&1; then
+		win32cxx="i686-w64-mingw32-g++"
+		win32flags="$win32flags -static-libgcc -static-libstdc++ -static"
+
+	elif command -v i686-pc-mingw32-g++ > /dev/null 2>&1; then
+		win32cxx="i686-pc-mingw32-g++"
+		win32flags="$win32flags -DMINGW32_FALLBACK -static-libgcc -static-libstdc++ -static"
+
+	elif command -v i586-mingw32msvc-c++ > /dev/null 2>&1; then
+		win32cxx="i586-mingw32msvc-c++"
+		win32flags="$win32flags -DMINGW32_FALLBACK -static-libgcc -static-libstdc++ -static"
+
+	else
+		echo "ERROR: No mingw32-g++ compiler found. Please use --win32cxx to specify one."
+		exit 1
+	fi
+fi
+
 # Get the version number
 changelog=$(head -n1 debian/changelog)
 if [[ "$changelog" =~ \((.*)\)\ (UNRELEASED)? ]]; then
@@ -111,9 +123,9 @@ fi
 
 # Normalize the paths
 prefix=$(readlink -m "$prefix")
+winepath=$(readlink -m "$winepath")
 mozpluginpath=$(readlink -m "$mozpluginpath")
 gccruntimedlls=$(readlink -m "$gccruntimedlls")
-winepath=$(readlink -m "$winepath")
 
 echo "Configuration Summary"
 echo "---------------------"
@@ -127,7 +139,6 @@ echo " gccruntimedlls    = '$gccruntimedlls'"
 echo " quietinstallation = '$quietinstallation'"
 echo " win32cxx          = '$win32cxx'"
 echo " win32flags        = '$win32flags'"
-echo " pluginloader      = '$pluginloader'"
 echo " nogpuaccel        = '$nogpuaccel'"
 echo ""
 echo "IMPORTANT: Please ensure you have XATTR support enabled for both wine and"
@@ -142,7 +153,6 @@ echo "gccruntimedlls=$gccruntimedlls"		>> config.make
 echo "quietinstallation=$quietinstallation" >> config.make
 echo "win32cxx=$win32cxx"					>> config.make
 echo "win32flags=$win32flags" 				>> config.make
-echo "pluginloader=$pluginloader"			>> config.make
 echo "nogpuaccel=$nogpuaccel"				>> config.make
 
 exit 0
