Move installation logic into plugin configuration files.

diff --git a/share/configs/pipelight-shockwave b/share/configs/pipelight-shockwave
--- a/share/configs/pipelight-shockwave
+++ b/share/configs/pipelight-shockwave
@@ -6,5 +6,62 @@
 # # dllPath           = C:\windows\system32\Adobe\Director\
 # # dllName           = np32dsw_1204144.dll
 # regKey              = @adobe.com/ShockwavePlayer
-# dependency          = wine-shockwave-installer
 # ---END CONFIG---
+
+install_shockwave()
+{
+    # http://get.adobe.com/de/shockwave/otherversions/
+    local URL="http://fpdownload.macromedia.com/get/shockwave/default/english/win95nt/latest/sw_lic_full_installer.exe"
+    local SHA="4c50d3f64372a9e242f13d8a12d3f5ef091b4a59ade48f8d878557d62ec74c3f"
+    local VER="1225195"
+
+    if ! download "$URL" "$SHA" "shockwave" ""; then
+        echo "[shockwave] ERROR: Download failed." >&2
+        return 1
+    fi
+
+    # Launch the installer
+    if [ "$QUIETINSTALLATION" -eq 0 ]; then
+        "$WINE" "$DOWNLOADFILE" 2>&1
+    else
+        "$WINE" "$DOWNLOADFILE" /S 2>&1 | progressbar "Please wait, installing ..." "Running Shockwave installer"
+    fi
+
+    local installdir1="$WINEPREFIX/drive_c/windows/system32/Adobe/Director"
+    local installdir2="$WINEPREFIX/drive_c/windows/syswow64/Adobe/Director"
+    if [ ! -f "$installdir1/np32dsw_$VER.dll" ] && [ ! -f "$installdir2/np32dsw_$VER.dll" ]; then
+        echo "[shockwave] ERROR: Installer did not run correctly or was aborted." >&2
+        return 1
+    fi
+
+     # Switch to OpenGL mode and disable fallback mode
+     local tmpfile=$(mktemp)
+     [ -f "$tmpfile" ] || return 1
+
+    (
+        echo "REGEDIT4"
+        echo ""
+        echo "[HKEY_CURRENT_USER\\Software\\Adobe\\Shockwave 12\\allowfallback]"
+        echo "@=\"n\""
+        echo ""
+        echo "[HKEY_CURRENT_USER\\Software\\Adobe\\Shockwave 12\\renderer3dsetting]"
+        echo "@=\"2\""
+        echo ""
+        echo "[HKEY_CURRENT_USER\\Software\\Adobe\\Shockwave 12\\renderer3dsettingPerm]"
+        echo "@=\"2\""
+    ) > "$tmpfile"
+
+    "$WINE" regedit "$tmpfile"
+    local res=$?
+
+    # Cleanup
+    rm "$tmpfile"
+
+    return "$res"
+}
+
+install_plugin()
+{
+    install_shockwave
+    return $?
+}
diff --git a/share/configs/pipelight-unity3d b/share/configs/pipelight-unity3d
--- a/share/configs/pipelight-unity3d
+++ b/share/configs/pipelight-unity3d
@@ -8,5 +8,36 @@
 # # dllName           = npUnity3D32.dll
 # regKey              = @unity3d.com/UnityPlayer,version=1.0
 # # fakeVersion       = Unity Player 4.2.2f1
-# dependency          = wine-unity3d-installer
 # ---END CONFIG---
+
+install_unity3d()
+{
+    # http://get.adobe.com/de/shockwave/otherversions/
+    local URL="http://webplayer.unity3d.com/download_webplayer-3.x/UnityWebPlayer.exe"
+    local SHA="9a5bcbe13bb74590e97ea4ee4fe76c24a5ac0b9cc99948e1be33ed3394d8c245"
+
+    if ! download "$URL" "$SHA" "unity3d" ""; then
+        echo "[unity3d] ERROR: Download failed." >&2
+        return 1
+    fi
+
+    if [ "$QUIETINSTALLATION" -eq 0 ]; then
+        "$WINE" "$DOWNLOADFILE" /AllUsers 2>&1
+    else
+        "$WINE" "$DOWNLOADFILE" /S /AllUsers 2>&1 | progressbar "Please wait, installing ..." "Running Unity3D plugin installer"
+    fi
+
+    local installdir="$WINEPREFIX/drive_c/Program Files/Unity/WebPlayer/loader"
+    if [ ! -f "$installdir/npUnity3D32.dll" ]; then
+        echo "[unity3d] ERROR: Installer did not run correctly or was aborted." >&2
+        return 1
+    fi
+
+    return 0
+}
+
+install_plugin()
+{
+    install_unity3d
+    return $?
+}
diff --git a/share/configs/pipelight-widevine b/share/configs/pipelight-widevine
--- a/share/configs/pipelight-widevine
+++ b/share/configs/pipelight-widevine
@@ -5,6 +5,32 @@
 # pluginLoaderPath    = $share/pluginloader.exe
 # dllPath             = C:\windows\system32
 # dllName             = npwidevinemediaoptimizer.dll
-# dependency          = wine-widevine-installer
 # experimental-forceSetWindow = true
 # ---END CONFIG---
+
+install_widevine()
+{
+    # http://www.widevine.com/download/videooptimizer/index.html
+    local URL="https://dl.google.com/widevine/6.0.0.12442/WidevineMediaOptimizer_Win.xpi"
+    local SHA="84cde1b83d8f5e4b287303a25e61227ce9a253268af6bd88b9a2f98c85129bc8"
+    local EXT="zip"
+
+    if ! download "$URL" "$SHA" "widevine" "$EXT"; then
+        echo "[widevine] ERROR: Download failed." >&2
+        return 1
+    fi
+
+    local system32="$WINEPREFIX/drive_c/windows/system32"
+    if ! unzip -p "$DOWNLOADFILE" "plugins/npwidevinemediaoptimizer.dll" > "$system32/npwidevinemediaoptimizer.dll"; then
+        echo "[widevine] ERROR: Unable to extract plugin from xip file." >&2
+        return 1
+    fi
+
+    return 0
+}
+
+install_plugin()
+{
+    install_widevine
+    return $?
+}
diff --git a/share/configs/pipelight-x64-unity3d b/share/configs/pipelight-x64-unity3d
--- a/share/configs/pipelight-x64-unity3d
+++ b/share/configs/pipelight-x64-unity3d
@@ -6,5 +6,36 @@
 # dllPath             = C:\Program Files\Unity\WebPlayer64\loader-x64
 # dllName             = npUnity3D64.dll
 # # regKey            = @unity3d.com/UnityPlayer,version=1.0
-# dependency          = wine-x64-unity3d-installer
 # ---END CONFIG---
+
+install_unity3d_x64()
+{
+    local URL="http://webplayer.unity3d.com/download_webplayer-3.x/UnityWebPlayerFull64.exe"
+    local SHA="38bb0ddb2e833786c5563af72624316759e2f6cfb5a0249c7f76357859d2262c"
+
+    if ! download "$URL" "$SHA" "unity3d-x64" ""; then
+        echo "[unity3d-x64] ERROR: Download failed." >&2
+        return 1
+    fi
+
+    # Launch the installer
+    if [ "$QUIETINSTALLATION" -eq 0 ]; then
+        "$WINE" "$DOWNLOADFILE" /AllUsers 2>&1
+    else
+        "$WINE" "$DOWNLOADFILE" /S /AllUsers 2>&1 | progressbar "Please wait, installing ..." "Running Unity3D x64 installer"
+    fi
+
+    local installdir="$WINEPREFIX/drive_c/Program Files/Unity/WebPlayer64/loader-x64"
+    if [ ! -f "$installdir/npUnity3D64.dll" ]; then
+        echo "[unity3d-x64] ERROR: Installer did not run correctly or was aborted." >&2
+        return 1
+    fi
+
+    return 0
+}
+
+install_plugin()
+{
+    install_unity3d_x64
+    return $?
+}
diff --git a/share/install-plugin b/share/install-plugin
--- a/share/install-plugin
+++ b/share/install-plugin
@@ -33,13 +33,12 @@ mktemp_with_ext()
 
 # > Checks if a dependency is already installed
 # arguments:
-# $1	- SHA256
-# $DEP
+# $1	- Date of last change
 is_installed()
 {
-	local SHA="$1"
-	local ckfile="$WINEPREFIX/$DEP.installed"
-	[ -f "$ckfile" ] && [ "$SHA" == "$(cat "$ckfile")" ]
+	local LASTCHANGE="$1"
+	local ckfile="$WINEPREFIX/$PLUGIN.installed"
+	[ -f "$ckfile" ] && [ "$LASTCHANGE" == "$(cat "$ckfile")" ]
 	return $?
 }
 
@@ -47,29 +46,30 @@ is_installed()
 # arguments: same as is_installed
 mark_installed()
 {
-	local SHA="$1"
-	local ckfile="$WINEPREFIX/$DEP.installed"
-	echo "$SHA" > "$ckfile"
+	local LASTCHANGE="$1"
+	local ckfile="$WINEPREFIX/$PLUGIN.installed"
+	echo "$LASTCHANGE" > "$ckfile"
 }
 
 # > Download a given dependency file
 # arguments:
 # $1	- URL
 # $2	- SHA256
-# $3	- Overwrite file extension
+# $3	- Name
+# $4	- Overwrite file extension
 # returns:
 # $DOWNLOADFILE
 DOWNLOADFILE=""
 download()
 {
-	local URL="$1";	local SHA="$2";	local EXT="$3"
+	local URL="$1";	local SHA="$2"; local NAME="$3"; local EXT="$4"
 
 	if [ -z "$EXT" ]; then
 		EXT=$(echo "$URL" | sed 's/.*\.//')
 	fi
 
 	# Reuse existing download
-	local dlfile="/tmp/pipelight-$DEP.$EXT"
+	local dlfile="/tmp/pipelight-$NAME.$EXT"
 	if [ -f "$dlfile" ] && [ "$SHA" == "$(sha256sum "$dlfile" | cut -d' ' -f1)" ]; then
 		DOWNLOADFILE="$dlfile"
 		return 0
@@ -84,7 +84,7 @@ download()
 	while true; do
 		if [ "$trycount" -le 0 ]; then
 			rm "$tmpfile"
-			echo "[$PRG] ERROR: Downloading of $DEP failed multiple times. Please check:" >&2
+			echo "[$PRG] ERROR: Downloading of $NAME failed multiple times. Please check:" >&2
 			echo "[$PRG]" >&2
 			echo "[$PRG]        * that your internet connection is working properly" >&2
 			echo "[$PRG]" >&2
@@ -96,7 +96,7 @@ download()
 			return 1
 		fi
 
-		download_file "$tmpfile" "$URL" 2>&1 | progressbar "Please wait, downloading ..." "Downloading $DEP ($filesize MiB)"
+		download_file "$tmpfile" "$URL" 2>&1 | progressbar "Please wait, downloading ..." "Downloading $NAME ($filesize MiB)"
 		if [ -f "$tmpfile" ] && [ "$SHA" == "$(sha256sum "$tmpfile" | cut -d' ' -f1)" ]; then
 			break
 		fi
@@ -118,68 +118,21 @@ download()
 	return 0
 }
 
-# > Installer for Silverlight
-# arguments:
-# $1	- version
-# $2	- short version
-# $DOWNLOADFILE
-install_silverlight()
-{
-	local VER="$1"
-	local SHORTVER="$2"
-
-	# Remove the registry keys for Silverlight since other versions can prevent this one from installing
-	"$WINE" msiexec /uninstall {89F4137D-6C26-4A84-BDB8-2E5A4BB71E00};
-
-	# Launch the installer
-	if [ "$QUIETINSTALLATION" -eq 0 ]; then
-		"$WINE" "$DOWNLOADFILE" /noupdate 2>&1
-	else
-		"$WINE" "$DOWNLOADFILE" /q /doNotRequireDRMPrompt /noupdate 2>&1 | progressbar "Please wait, installing ..." "Running $DEP"
-	fi
-
-	local programfiles="$WINEPREFIX/drive_c/Program Files"
-	if [ ! -d "$programfiles/Microsoft Silverlight/$VER" ]; then
-		echo "[$PRG] ERROR: Installer for $DEP did not run correctly or was aborted." >&2
-		return 1
-	fi
-
-	# Move the installation to a version-specific folder that nothing will touch
-	mkdir -p "$programfiles/Silverlight"
-	mv "$programfiles/Microsoft Silverlight/$VER" "$programfiles/Silverlight/$VER"
-
-	# Create a short symlink if SHORTVER is provided.
-	if [ ! -z "$SHORTVER" ]; then
-		local shortsymlink="$programfiles/Silverlight/$SHORTVER"
-		if [ -L "$shortsymlink" ]; then
-			rm "$shortsymlink"
-		elif [ -e "$shortsymlink" ]; then
-			echo "[$PRG] ERROR: Unable to overwrite $shortsymlink, please delete this file manually." >&2
-			return 1
-		fi
-		ln -s "$VER" "$shortsymlink"
-	fi
-
-	# Remove the Silverlight menu shortcut
-	rm -f "$WINEPREFIX/drive_c/users/$USER/Start Menu/Programs/Microsoft Silverlight/Microsoft Silverlight.lnk"
-
-	# Successful
-	return 0
-}
 
 # > Extract cab library
 # arguments:
-# $1	- file to extract
-# $DOWNLOADFILE
+# $1	- cab file
+# $2	- file to extract
 #
 # optional arguments:
 # --reg - run regsvr32.dll to register the dll
 install_cabextract()
 {
+	local CABFILE="$1"; shift
 	local FILE="$1"; shift
 
 	local system32="$WINEPREFIX/drive_c/windows/system32"
-	cabextract -d "$system32" "$DOWNLOADFILE" -F "$FILE"
+	cabextract -d "$system32" "$CABFILE" -F "$FILE"
 	if [ ! -f "$system32/$FILE" ]; then
 		echo "[$PRG] ERROR: Failed to extract $FILE from cab file." >&2
 		return 1
@@ -205,166 +158,6 @@ install_cabextract()
 				;;
 		esac
 	done
-
-	# Successful
-	return 0
-}
-
-# > Install flash
-# arguments:
-# $1	- version path component
-# $DOWNLOADFILE
-install_flash()
-{
-	VER="$1"
-
-	# Launch the installer
-	if [ "$QUIETINSTALLATION" -eq 0 ]; then
-		"$WINE" "$DOWNLOADFILE" 2>&1
-	else
-		"$WINE" "$DOWNLOADFILE" -install 2>&1 | progressbar "Please wait, installing ..." "Running $DEP"
-	fi
-
-	local installdir="$WINEPREFIX/drive_c/windows/system32/Macromed/Flash"
-
-	local result=1
-	case "$WINEARCH" in
-		win32)
-			[ -f "$installdir/NPSWF32_$VER.dll" ]; result=$?
-			;;
-		win64)
-			[ -f "$installdir/NPSWF64_$VER.dll" ]; result=$?
-			;;
-		*)
-			[ -f "$installdir/NPSWF32_$VER.dll" ] || [ -f "$installdir/NPSWF64_$VER.dll" ]; result=$?
-			;;
-	esac
-
-	if [ "$result" -ne 0 ]; then
-		echo "[$PRG] ERROR: Installer for $DEP did not run correctly or was aborted." >&2
-		return 1
-	fi
-
-
-	local flashconfig="$installdir/mms.cfg"
-	if ! grep -q "^OverrideGPUValidation=" "$flashconfig" 2>/dev/null; then
-		(
-			grep -v "^OverrideGPUValidation=" "$flashconfig" 2>/dev/null
-			echo "OverrideGPUValidation=true"
-		) > "$flashconfig.bak"
-
-		if ! mv "$flashconfig.bak" "$flashconfig"; then
-			echo "[$PRG] ERROR: Unable to change $DEP plugin settings." >&2
-		fi
-	fi
-
-	# Successful
-	return 0
-}
-
-# > Install shockwave
-# arguments:
-# $1	- version path component
-# $DOWNLOADFILE
-install_shockwave()
-{
-	VER="$1"
-
-	# Launch the installer
-	if [ "$QUIETINSTALLATION" -eq 0 ]; then
-		"$WINE" "$DOWNLOADFILE" 2>&1
-	else
-		"$WINE" "$DOWNLOADFILE" /S 2>&1 | progressbar "Please wait, installing ..." "Running $DEP"
-	fi
-
-	local installdir1="$WINEPREFIX/drive_c/windows/system32/Adobe/Director"
-	local installdir2="$WINEPREFIX/drive_c/windows/syswow64/Adobe/Director"
-	if [ ! -f "$installdir1/np32dsw_$VER.dll" ] && [ ! -f "$installdir2/np32dsw_$VER.dll" ]; then
-		echo "[$PRG] ERROR: Installer for $DEP did not run correctly or was aborted." >&2
-		return 1
-	fi
-
-	 # Switch to OpenGL mode and disable fallback mode
-	 local tmpfile=$(mktemp)
-	 [ -f "$tmpfile" ] || return 1
-
-	(
-		echo "REGEDIT4"
-		echo ""
-		echo "[HKEY_CURRENT_USER\\Software\\Adobe\\Shockwave 12\\allowfallback]"
-		echo "@=\"n\""
-		echo ""
-		echo "[HKEY_CURRENT_USER\\Software\\Adobe\\Shockwave 12\\renderer3dsetting]"
-		echo "@=\"2\""
-		echo ""
-		echo "[HKEY_CURRENT_USER\\Software\\Adobe\\Shockwave 12\\renderer3dsettingPerm]"
-		echo "@=\"2\""
-	) > "$tmpfile"
-
-	"$WINE" regedit "$tmpfile"
-	local res=$?
-
-	# Cleanup
-	rm "$tmpfile"
-
-	# Successful
-	return "$res"
-}
-
-# > Install Unity3D 32 bit
-# arguments: None
-# $DOWNLOADFILE
-install_unity3d()
-{
-	# Launch the installer
-	if [ "$QUIETINSTALLATION" -eq 0 ]; then
-		"$WINE" "$DOWNLOADFILE" /AllUsers 2>&1
-	else
-		"$WINE" "$DOWNLOADFILE" /S /AllUsers 2>&1 | progressbar "Please wait, installing ..." "Running $DEP"
-	fi
-
-	local installdir="$WINEPREFIX/drive_c/Program Files/Unity/WebPlayer/loader"
-	if [ ! -f "$installdir/npUnity3D32.dll" ]; then
-		echo "[$PRG] ERROR: Installer for $DEP did not run correctly or was aborted." >&2
-		return 1
-	fi
-
-	# Successful
-	return 0
-}
-
-# > Install Unity3D 64 bit
-# arguments: None
-# $DOWNLOADFILE
-install_x64_unity3d()
-{
-	# Launch the installer
-	if [ "$QUIETINSTALLATION" -eq 0 ]; then
-		"$WINE" "$DOWNLOADFILE" /AllUsers 2>&1
-	else
-		"$WINE" "$DOWNLOADFILE" /S /AllUsers 2>&1 | progressbar "Please wait, installing ..." "Running $DEP"
-	fi
-
-	local installdir="$WINEPREFIX/drive_c/Program Files/Unity/WebPlayer64/loader-x64"
-	if [ ! -f "$installdir/npUnity3D64.dll" ]; then
-		echo "[$PRG] ERROR: Installer for $DEP did not run correctly or was aborted." >&2
-		return 1
-	fi
-
-	# Successful
-	return 0
-}
-
-# > Install Widevine
-# arguments: None
-# $DOWNLOADFILE
-install_widevine()
-{
-	local system32="$WINEPREFIX/drive_c/windows/system32"
-	if ! unzip -p "$DOWNLOADFILE" "plugins/npwidevinemediaoptimizer.dll" > "$system32/npwidevinemediaoptimizer.dll"; then
-		echo "[$PRG] ERROR: Unable to extract plugin from xip file." >&2
-		return 1
-	fi
 
 	# Successful
 	return 0
@@ -474,8 +267,8 @@ else
 fi
 
 # Abort if no arguments were given
-if [ $# -eq 0 ]; then
-	echo "[$PRG] ERROR: Please provide a path to a plugin config." >&1
+if [ $# -ne 2 ]; then
+	echo "[$PRG] ERROR: Please provide a path to a plugin config and a plugin name." >&2
 	exit 1
 fi
 
@@ -493,6 +286,14 @@ if [ ! -w "$WINEPREFIX" ]; then
 	fi
 fi
 
+PLUGIN_SCRIPT="$1"
+PLUGIN="$2"
+
+if [ ! -f "$PLUGIN_SCRIPT" ]; then
+	echo "[$PRG] ERROR: Plugin script $PLUGIN_SCRIPT does not exist" >&2
+	exit 1
+fi
+
 # Silent installation
 if [ -z "$QUIETINSTALLATION" ]; then
 	QUIETINSTALLATION=0
@@ -505,7 +306,7 @@ LOCKFILE="/tmp/wine-$LOCKFILE.tmp"
 LOCKFD=9; eval "exec $LOCKFD> \"\$LOCKFILE\""
 if ! flock -x -w 360 "$LOCKFD"; then
 	echo "[$PRG] ERROR: Failed to obtain an installation lock in 6 minutes." >&2
-	exit 1;
+	exit 1
 fi
 
 # Close file descriptor (ensure that the lock is released when the installation is ready)
@@ -525,94 +326,23 @@ if [ ! -f "$WINEPREFIX/system.reg" ]; then
 	DISPLAY="" "$WINE" wineboot.exe 2>&1 | progressbar "Please wait..." "Creating wine prefix"
 fi
 
-# Set default return value
-RET=0
+file_date=$(date -u -Ins -r "$PLUGIN_SCRIPT")
 
-echo "[$PRG] FIXME: Load config file from $1" >&2
-shift
+# Is already installed?
+if is_installed "$file_date"; then
+	echo "[$PRG] $PLUGIN is already installed in '$WINEPREFIX'."
+	exit 0
+fi
 
-while [ $# -gt 0 ] ; do
-	DEP="$1"; INS=(); URL=""; SHA=""; EXT=""; DOWNLOADFILE=""; shift
-	case "$DEP" in
-		wine-prefix)
-			continue # The wine-prefix is created automatically for all packages
-			;;
-		wine-silverlight5.0-installer)
-			INS=(install_silverlight "5.0.61118.0")
-			URL="http://silverlight.dlservice.microsoft.com/download/5/5/7/55748E53-D673-4225-8072-4C7A377BB513/runtime/Silverlight.exe"
-			SHA="dd45a55419026c592f8b6fc848dceface7e1ce98720bf13848a2e8ae366b29e8"
-			;;
-		wine-silverlight5.1-installer) # http://www.microsoft.com/getsilverlight/locale/en-us/html/Microsoft%20Silverlight%20Release%20History.htm
-			INS=(install_silverlight "5.1.41212.0" "latest")
-			URL="http://download.microsoft.com/download/5/3/D/53D3880B-25F8-4714-A4AC-E463A492F96E/41212.00/Silverlight.exe"
-			SHA="af2d435a034e03c2940a648291013ebd9de20d855447dbdb93416e7e03c3e91b"
-			;;
-		wine-flash-installer) # http://www.adobe.com/de/software/flash/about/
-			INS=(install_flash "23_0_0_185")
-			URL="http://fpdownload.macromedia.com/get/flashplayer/pdc/23.0.0.185/install_flash_player.exe"
-			SHA="9d6407d54127a84c55f23662d9eb02a293f2956b05c3fad3cc29e7ec6b1b22f2"
-			;;
-		wine-widevine-installer) # http://www.widevine.com/download/videooptimizer/index.html
-			INS=(install_widevine)
-			URL="https://dl.google.com/widevine/6.0.0.12442/WidevineMediaOptimizer_Win.xpi"
-			SHA="84cde1b83d8f5e4b287303a25e61227ce9a253268af6bd88b9a2f98c85129bc8"
-			EXT="zip"
-			;;
-		wine-unity3d-installer)
-			INS=(install_unity3d)
-			URL="http://webplayer.unity3d.com/download_webplayer-3.x/UnityWebPlayer.exe"
-			SHA="9a5bcbe13bb74590e97ea4ee4fe76c24a5ac0b9cc99948e1be33ed3394d8c245"
-			;;
-		wine-x64-unity3d-installer)
-			INS=(install_x64_unity3d)
-			URL="http://webplayer.unity3d.com/download_webplayer-3.x/UnityWebPlayerFull64.exe"
-			SHA="f612da4f81aa2a0e8e693332e51ca424ff0b5948478df6e17515a0a9b3387811"
-			;;
-		wine-shockwave-installer) # http://get.adobe.com/de/shockwave/otherversions/
-			INS=(install_shockwave "1224194")
-			URL="http://fpdownload.macromedia.com/get/shockwave/default/english/win95nt/latest/sw_lic_full_installer.exe"
-			SHA="add6e1e1b5ac6f28eadb06a6b0220423a48c554ca4cbd212727dc79bc365ca7e"
-			;;
-		wine-mpg2splt-installer)
-			INS=(install_cabextract mpg2splt.ax --reg)
-			URL="http://download.microsoft.com/download/8/0/D/80D7E79D-C0E4-415A-BCCA-E229EAFE2679/dshow_nt.cab"
-			SHA="984ed15e23a00a33113f0012277e1e680c95782ce2c44f414e7af14e28e3f1a2"
-			;;
-		wine-wininet-installer)
-			echo "[$PRG] Ignoring deprecated $DEP."
-			continue
-			;;
-		*)
-			echo "[$PRG] ERROR: No installer script found for $DEP." >&2
-			RET=1
-			break
-			;;
-	esac
+echo "[$PRG] Running $PLUGIN installation script."
 
-	# Is already installed?
-	if is_installed "$SHA"; then
-		echo "[$PRG] $DEP is already installed in '$WINEPREFIX'."
-		continue
-	fi
+source "$PLUGIN_SCRIPT"
+if ! install_plugin; then
+	echo "[$PRG] ERROR: Installation script for $PLUGIN failed." >&2
+	exit 1
+fi
 
-	echo "[$PRG] Downloading and running $DEP."
+# Mark the package as installed
+mark_installed "$file_date"
 
-	# Fetch the download
-	if ! download "$URL" "$SHA" "$EXT"; then
-		echo "[$PRG] ERROR: Download of $DEP failed." >&2
-		RET=1
-		break
-	fi
-
-	# Do the installation
-	if ! eval "${INS[@]}"; then
-		echo "[$PRG] ERROR: Execution of $DEP failed." >&2
-		RET=1
-		break
-	fi
-
-	# Mark the package as installed
-	mark_installed "$SHA"
-done
-
-exit "$RET"
+exit 0
